# Generated by Django 3.0.6 on 2020-07-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BTTVapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_id',
            field=models.IntegerField(default=0),
        ),
    ]
