# Generated by Django 3.0.6 on 2020-07-09 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BTTVapp', '0003_auto_20200708_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='BTTVapp.Regions'),
        ),
    ]
